UPDATE
conditional adition (line 60) to execute the methods created. Still returning 'TypeError: openCamera() missing 1 required positional argument: 'link'' on the server, but it is printing the right value on terminal.